### ISSUE TITLE
Add project description

### ISSUE THREAD

**Issue by denizdogan** [pingyuanChen/webpack-uglify-js-plugin#1]
It looks like this is a newer and faster version of an UglifyJS plugin, so I'm very interested to know more. What are the main differences between this and `webpack.optimize.UglifyJsPlugin`?

**Comment by genintho** [comment]
It is writing to disk some of the compilation artifact and reuse them on future compilation if the input did not change.
I tried to submit a PR against the official Webpack repo to do something similar, but I never got any feedback 😿 https://github.com/webpack/webpack/pull/2165.

**Comment by pingyuanChen** [comment]
@denizdogan  Uglify take a long time to run, especially for a large project with many bundles, so this UglifyJS plugin will add cache for all bundles to avoid unnecessary uglifying if the bundle did not change.

**Comment by denizdogan** [comment]
No longer relevant to me, closing
